from typing import Tuple

from cms.forms.fields import PageSelectFormField
from django import forms

from menu_builder.models import NavigationLink


class NavigationLinkModelForm(forms.ModelForm):
    """Navigation Link Model Form."""
    class Meta:
        model = NavigationLink
        exclude: Tuple[str] = ()

    internal_link = PageSelectFormField(required=False)


class NavigationLinkModelFormNoTrans(NavigationLinkModelForm):
    """
    Navigation Link Model Form No Transactions.

    To prevent displaying translation fields (generated by modeltranlations.)
    """
    class Meta:
        model = NavigationLink
        fields: Tuple[str] = (
            'menu',
            'label',
            'external_link',
            'internal_link',
            'icon',
            'open_in_new_tab',
            'parent',
        )
