# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.CreateModel(
            name='MenuPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='menu_builder_menuplugin', serialize=False, to='cms.CMSPlugin')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_builder.Menu')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='NavigationLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='label')),
                ('label_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='label')),
                ('label_hi', models.CharField(blank=True, max_length=100, null=True, verbose_name='label')),
                ('label_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='label')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='external link')),
                ('icon', models.CharField(blank=True, help_text='an Icon from our icon/font framework, for instance "fa fa-login"', max_length=25, null=True, verbose_name='icon')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='open in new tab')),
                ('link_order', models.PositiveIntegerField(default=0)),
                ('internal_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page', verbose_name='internal link')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='menu_builder.Menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu_builder.NavigationLink')),
            ],
            options={
                'verbose_name': 'Navigation Link',
                'verbose_name_plural': 'Navigation Links',
                'ordering': ('link_order',),
            },
        ),
    ]
