# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_builder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationlink',
            name='label_hi',
        ),
        migrations.RemoveField(
            model_name='navigationlink',
            name='label_ru',
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='label_fa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='label'),
        ),
    ]
