# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 13:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0016_auto_20160608_1535'),
        ('planet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='section',
            name='name_hi',
        ),
        migrations.RemoveField(
            model_name='section',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='sectionitem',
            name='link',
        ),
        migrations.AddField(
            model_name='section',
            name='css_classes',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='css classes'),
        ),
        migrations.AddField(
            model_name='section',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Can be used for background image or the whole section.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='section',
            name='title',
            field=models.CharField(default='fill me up', help_text='Public title of the section, visitors will be able to see it.', max_length=250, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='title_en',
            field=models.CharField(help_text='Public title of the section, visitors will be able to see it.', max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='section',
            name='title_hi',
            field=models.CharField(help_text='Public title of the section, visitors will be able to see it.', max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='section',
            name='title_ru',
            field=models.CharField(help_text='Public title of the section, visitors will be able to see it.', max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='sectionitem',
            name='external_link',
            field=models.URLField(blank=True, null=True, verbose_name='external link'),
        ),
        migrations.AddField(
            model_name='sectionitem',
            name='external_link_en',
            field=models.URLField(blank=True, null=True, verbose_name='external link'),
        ),
        migrations.AddField(
            model_name='sectionitem',
            name='external_link_hi',
            field=models.URLField(blank=True, null=True, verbose_name='external link'),
        ),
        migrations.AddField(
            model_name='sectionitem',
            name='external_link_ru',
            field=models.URLField(blank=True, null=True, verbose_name='external link'),
        ),
        migrations.AddField(
            model_name='sectionitem',
            name='internal_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page', verbose_name='internal link'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(help_text='Internal user only.', max_length=250, verbose_name='name'),
        ),
    ]
