# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0002_auto_20171130_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='secondary_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='secondary image'),
        ),
        migrations.AddField(
            model_name='section',
            name='sub_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='section',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='section',
            name='sub_title_hi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='section',
            name='sub_title_ru',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='sub title'),
        ),
    ]
