# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0002_auto_20171130_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverplugin',
            name='is_scroll',
            field=models.BooleanField(default=False, verbose_name='is scroll'),
        ),
    ]
