# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0003_auto_20171202_1636'),
        ('planet', '0003_coverplugin_is_scroll'),
    ]

    operations = [
    ]
