# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 09:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('planet', '0004_merge_20171203_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverplugin',
            name='inside_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inside_image', to=settings.FILER_IMAGE_MODEL, verbose_name='inside image'),
        ),
        migrations.AlterField(
            model_name='coverplugin',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_image', to=settings.FILER_IMAGE_MODEL, verbose_name='image'),
        ),
    ]
