# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-03 09:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0007_auto_20180103_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='secondary_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_images', to=settings.FILER_IMAGE_MODEL, verbose_name='secondary image'),
        ),
    ]
