# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-03 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0007_auto_20180103_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='secondary_image',
        ),
    ]
